Задача: написать дерево, перевести из json в код

In [9]:
import json

def dict_to_tree(result, tree, parent):
    for x in tree:
        for i in tree[x]:
            result.append([int(x), int(i)])
        dict_to_tree(result, tree[x], x)

def json_to_tree(file_name):
    result = []
    with open(file_name, "r") as file:
        tree = json.loads(file.read())
    #print(tree)

    dict_to_tree(result, tree, 0)
    return result


file_name = "tree.json"
print(json_to_tree(file_name))

[[1, 2], [2, 3], [2, 4], [3, 5], [3, 6], [4, 7], [4, 8]]


Функции для представления дерева в другом виде:

In [8]:
import numpy as np

def to_matrix(ribs):
    n = len(ribs) + 1
    matrix = np.zeros((n,n), dtype=int)
    for x in ribs:
        a = x[0] - 1
        b = x[1] - 1
        matrix[a][b] = 1
        matrix[b][a] = 1
    return matrix


list_of_ribs = json_to_tree("tree.json")
print(to_matrix(list_of_ribs))

[[0 1 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0]
 [0 1 0 0 1 1 0 0]
 [0 1 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [11]:
import numpy as np

def to_array(ribs):
    n = len(ribs) + 1
    array = np.zeros(n)
    for x in ribs:
        a = x[0]
        b = x[1] - 1
        array[b] = a
    return array


list_of_ribs = json_to_tree("tree.json")
print(to_array(list_of_ribs))

[0. 1. 2. 2. 3. 3. 4. 4.]
